version: '2'
services:
  nodejs-server:
    build:
      context: ./backend
  backend:
    image: node
    volumes: 
    - ./backend:/app
    working_dir: /app
    command: DEBUG=app:* npm start
    ports:
      - 8080:3000  
  frontend:  
    image: node
    volumes: 
    - ./frontend:/my-app
    working_dir: /app

  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/